DEBS_TARBALL:
  packages:
  - name: containerd.io
    version: 1.2.13-2
  - name: docker-ce
    version: 5:19.03.12~3-0~ubuntu-xenial
  - name: docker-ce-cli
    version: 5:19.03.12~3-0~ubuntu-xenial
  - name: iptables
    version: 1.6.0-2ubuntu3
  - name: libnfnetlink0
    version: 1.0.1-3
  - name: libxtables11
    version: 1.6.0-2ubuntu3
